name: Blog CI/CD

on:
  push:
    branches:
      - source

permissions:
  contents: write

env:
  TZ: Asia/Shanghai

jobs:
  blog-cicd:
    name: Hexo Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: |
          npm install -g hexo-cli
          npm install

      - name: Generate Static Files
        run: |
          hexo clean
          hexo generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: main
          force_orphan: true

          user_name: yicizhang00
          user_email: zhangyici2000@outlook.com

          commit_message: |
            deploy: site updated at $(date +"%Y-%m-%d %H:%M:%S")